### ISSUE TITLE
[UX] Modal dialog overlay width too narrow when trying to edit ckedit fields... this helps.

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/seventy#1]
Thought this may be of interest to add to your examples...

In the Seven theme, the layout-dialog is set at 600px.  I found this very limiting when editing CKEditor content so I created a subtheme and put

```
.layout-dialog {
	max-width: 75%;
}
```

It makes the modal overlays a lot more usable.

Hope this helps.

**Comment by olafgrabienski** [comment]
Many thanks for sharing the modified styling for the Layout dialog, great idea! I'm definitely interested to include your example, and even more. I guess the [Wiki](https://github.com/backdrop-contrib/seventy/wiki) would be a good place, what do you think about it? Once there is at least one example in the Wiki, I'd put a link to it in the README.

Regarding the Layout dialog, personally I wouldn't apply the 75% on narrow screens but wrap it in a media query, something like the following:

```

@media (min-width: 768px) {
  .layout-dialog {
    max-width: 75%;
  }
}
```

**Comment by albanycomputers** [comment]
Even better :-)

I only edit on a large screen so 75% is what I found usable :-)

I'd change the width to 100% for anything less than 767... may as well maximise the space :-)
```
@media (max-width: 767px) {
  .layout-dialog {
    max-width: 100%;
  }
}
```

**Comment by olafgrabienski** [comment]
I've finally created the [Wiki page](https://github.com/backdrop-contrib/seventy/wiki/Usage-examples) and put a link to it in the README.

Thanks again for sharing your example. Feel free to edit it in the Wiki, and/or to add more.
